### PR TITLE
Getting initial LinkState 2015 material up

### PR DESCRIPTION
**Pull request by thomasrussellmurphy**
It's a start! Got LinkState 2015 pages up and connected. Lots of work to do on making it functional and content to add, but it looks like something.

### CODE REVIEW

**Comment by ajm188** [comment]
If we're going to merge this in as-is, we probably want to remove the mailto:TODO@case.edu, just in case someone actually has that alias.

**Comment by thomasrussellmurphy** [comment]
Someone does, but this isn't intended to be merged directly. I don't know how to work this app well enough to get much more than this to happen and could use some other contributions to make it postable.

**Comment by thomasrussellmurphy** [comment]
Tested under Ruby 2.2.1 and fresh `gem install bundle`, `bundle install`.

**Comment by StephHippo** [comment]
:+1:

**Pull request merged**
