### PR TITLE
Proper hard-wrapping of speaker bios and formatting touch-ups

### PR DESCRIPTION
**Pull request by thomasrussellmurphy**
No apparent regression in display of any of the archived conference pages. Formatting changes only, absolutely no content changed.

Formatted using TextWrangler's hard wrap to 80 lines, paragraph fill, no indentation (relative to first line).

### CODE REVIEW

**Comment by ajm188** [comment]
:ship: :it:

**Comment by thomasrussellmurphy** [comment]
Not deploying since there are no content changes.

**Comment by StephHippo** [comment]
Good habit to deploy anyway.

**Comment by thomasrussellmurphy** [comment]
Done.

**Pull request merged**
