### PR TITLE
Taking a try at adding a Twitter Card

### PR DESCRIPTION
**Pull request by thomasrussellmurphy**
Using *Padrino*'s feature for adding meta tags to a page, here are some card bits.

Edit: which of our Twitter accounts should this page/card be credited towards?

### CODE REVIEW

**Comment by ajm188** [comment]
I say it should be @cwruacm

**Comment by thomasrussellmurphy** [comment]
Indeed it is. Any suggestions for this first revision of the title/description or is this good?

**Comment by ajm188** [comment]
lg2m. @k4therin2 might have feedback, though

**Comment by k4therin2** [comment]
gucci

**Comment by thomasrussellmurphy** [comment]
Deployed.

**Pull request merged**
