### PR TITLE
Creating a Call-for-Speakers Section for Link-State 2015

### PR DESCRIPTION
**Pull request by thomasrussellmurphy**
Here's a section and a meta-statement about requesting attention from speakers. Suggestions for making some substance in this section?

### CODE REVIEW

**Comment by thomasrussellmurphy** [comment]
Thoughts?

**Comment by brenns10** [comment]
Sounds pretty professional to me.  Is there a proposal deadline that would be useful to put up?

**Comment by thomasrussellmurphy** [comment]
Considering previous schedules and how we've attracted speakers, I don't think a deadline would be of much use.

**Comment by brenns10** [comment]
I thought so, but I figured I'd try to brainstorm some "substance" ideas.  If attracting speakers is as much of a concern as you think, then I'd suggest shipping this now so we at least have a call for speakers to point to, and deal with any content issues as they happen.

**Comment by ajm188** [comment]
lol deadlines. merge it! :+1:

**Pull request merged**
