### PR TITLE
Put a short piece on HackCWRU up and a link to the current HackCWRU site

### PR DESCRIPTION
**Pull request by thomasrussellmurphy**
Dealing with the HackCWRU site can happen later, but this at least gives us some connection between the sites.

### CODE REVIEW

**Comment by ajm188** [comment]
:+1:

**Comment by thomasrussellmurphy** [comment]
Done.

**Comment by thomasrussellmurphy** [comment]
Any additional thoughts?

**Comment by ajm188** [comment]
Looks good :+1:

**Pull request merged**
