### PR TITLE
Change to mention 2.2.1, Creating Deploy information

### PR DESCRIPTION
**Pull request by thomasrussellmurphy**
Just updated README to mention 2.2.1 for local testing. Still need deploy information from @Aaronneyer. Further information expected Wednesday.

### CODE REVIEW

**Comment by thomasrussellmurphy** [comment]
This should also cover #33 when we're finished.

**Comment by StephHippo** [comment]
:+1:

**Comment by ajm188** [comment]
:+1:

**Comment by thomasrussellmurphy** [comment]
Will wait to merge for deploy information.

**Comment by Aaronneyer** [comment]
We should probably actually get this running on the Docker VM, because the current deploy instructions are a bit annoying and are going to need update when we update to 2.2.1 anyways. @matthewbentley should probably be able to help out with that.

**Comment by matthewbentley** [comment]
I will work on getting this in docker tomorrow / this weekend.

**Comment by thomasrussellmurphy** [comment]
Should the complete deploy instructions be on a different PR and merge this as it stands?

**Comment by Aaronneyer** [comment]
Ya, that would probably be best

**Pull request merged**
